version: 1
formatters:
  console:
    format: '%(message)s'
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detail:
    format: '%(asctime)s - %(levelname)s - File: %(filename)s - %(funcName)s() - Line: %(lineno)d -  %(message)s'

loggers:
  all:
    handlers: [all]
    propagate: true
  warn:
    handlers: [warn]
    propagate: true

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    stream: ext://sys.stdout
  all:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    when: W0
    backupCount: 4
    filename: /var/log/traversal/all.log
  debug:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: detail
    when: W0
    backupCount: 4
    filename: /var/log/traversal/debug.log
  warn:
    class: logging.handlers.TimedRotatingFileHandler
    level: WARNING
    formatter: detail
    when: W0
    backupCount: 4
    filename: /var/log/traversal/warn.log

root:
  level: DEBUG
  handlers: [console, all, warn, debug]
  propagate: true
